export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCES = 'FETCH_CITIES_SUCCES';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

export const FETCH_SCHEMA_REQUEST = 'FETCH_SCHEMA_REQUEST';
export const FETCH_SCHEMA_SUCCES = 'FETCH_SCHEMA_SUCCES';
export const FETCH_SCHEMA_FAILURE = 'FETCH_SCHEMA_FAILURE';

export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCES = 'CREATE_NEW_USER_SUCCES';
export const CREATE_NEW_USER_FAILURE = 'CREATE_NEW_USER_FAILURE';
